In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Lab2dataset.csv")

In [3]:
df

     Name  Age       City  Marks
0     Ali   19    Karachi   85.0
1    Sara   20     Lahore   78.0
2   Ahmed   19    Karachi   92.0
3  Ayesha   21  Islamabad    NaN
4   Bilal   18    Karachi   67.0
5    Hina   20     Lahore   88.0
6     Ali   19    Karachi   85.0
7   Usman   22   Peshawar   74.0
8    Zara   19    Karachi   90.0
9  Fatima   20     Lahore    NaN

In [4]:
df.head()

     Name  Age       City  Marks
0     Ali   19    Karachi   85.0
1    Sara   20     Lahore   78.0
2   Ahmed   19    Karachi   92.0
3  Ayesha   21  Islamabad    NaN
4   Bilal   18    Karachi   67.0

In [5]:
df.tail()

     Name  Age      City  Marks
5    Hina   20    Lahore   88.0
6     Ali   19   Karachi   85.0
7   Usman   22  Peshawar   74.0
8    Zara   19   Karachi   90.0
9  Fatima   20    Lahore    NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Marks   8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [7]:
df.shape

(10, 4)

In [8]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [9]:
df.loc[0]

Name         Ali
Age           19
City     Karachi
Marks       85.0
Name: 0, dtype: object

In [10]:
df.loc[0:3, ['Name','Marks']]

     Name  Marks
0     Ali   85.0
1    Sara   78.0
2   Ahmed   92.0
3  Ayesha    NaN

In [11]:
df.iloc[0:3, 1:3]

   Age     City
0   19  Karachi
1   20   Lahore
2   19  Karachi

In [12]:
df[['Name','Marks']]

     Name  Marks
0     Ali   85.0
1    Sara   78.0
2   Ahmed   92.0
3  Ayesha    NaN
4   Bilal   67.0
5    Hina   88.0
6     Ali   85.0
7   Usman   74.0
8    Zara   90.0
9  Fatima    NaN

In [13]:
df[df['Marks'] > 80]

    Name  Age     City  Marks
0    Ali   19  Karachi   85.0
2  Ahmed   19  Karachi   92.0
5   Hina   20   Lahore   88.0
6    Ali   19  Karachi   85.0
8   Zara   19  Karachi   90.0

In [14]:
df.isnull().sum()

Name     0
Age      0
City     0
Marks    2
dtype: int64

In [15]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [16]:
df.isnull().sum()

Name     0
Age      0
City     0
Marks    0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(1)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      object
 1   Age     9 non-null      int64
 2   City    9 non-null      object
 3   Marks   9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 360.0+ bytes

In [21]:
df.head()

     Name  Age       City   Marks
0     Ali   19    Karachi  85.000
1    Sara   20     Lahore  78.000
2   Ahmed   19    Karachi  92.000
3  Ayesha   21  Islamabad  82.375
4   Bilal   18    Karachi  67.000