In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("students.csv")

In [3]:
df.head()

    Name  Age   Marks
0    NaN   NaN    NaN
1    Ali  20.0   85.0
2   Sara  19.0   92.0
3  Ahmed  21.0   76.0
4   Zain  22.0   65.0

In [4]:
df.tail()

     Name  Age   Marks
6    Omar  23.0   72.0
7    Anum  19.0   95.0
8   Bilal  21.0   80.0
9    Sana  22.0   90.0
10  Hamza  20.0   70.0

In [8]:
# rows
df.shape[0]

11

In [6]:
# columns
df.columns

Index(['Name', 'Age ', 'Marks'], dtype='object')

In [7]:
# data_types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     float64
 2   Marks   10 non-null     float64
dtypes: float64(2), object(1)
memory usage: 396.0+ bytes

In [9]:
df2 = pd.read_csv("inventory_dataset.csv")

In [10]:
df2.head()

,ProductID,ProductName,Category,QuantityInStock,UnitPrice,Supplier,DateAdded,Warehouse
0,1001,Wireless Mouse,Electronics,150,12.99,TechSupply Co.,2025-01-15,Warehouse A
1,1002,Bluetooth Keyboard,Electronics,85,24.50,TechSupply Co.,2025-01-15,Warehouse A
2,1003,Office Chair,Furniture,40,89.99,ComfortSeating Ltd.,2025-02-03,Warehouse B
3,1004,Standing Desk,Furniture,20,199.00,ComfortSeating Ltd.,2025-02-03,Warehouse B
4,1005,LED Monitor 24in,Electronics,60,145.75,TechSupply Co.,2025-02-10,Warehouse A

In [11]:
df2.tail()

,ProductID,ProductName,Category,QuantityInStock,UnitPrice,Supplier,DateAdded,Warehouse
15,1016,Sticky Notes Pack,Stationery,350,2.99,PaperWorks Inc.,2025-01-30,Warehouse C
16,1017,Conference Table,Furniture,10,350.00,ComfortSeating Ltd.,2025-02-20,Warehouse B
17,1018,External Hard Drive 1TB,Electronics,70,59.99,TechSupply Co.,2025-03-15,Warehouse A
18,1019,Highlighter Set,Stationery,260,3.99,PaperWorks Inc.,2025-02-01,Warehouse C
19,1020,Bookshelf,Furniture,30,145.00,ComfortSeating Ltd.,2025-02-25,Warehouse B

In [12]:
# rows
df2.shape[0]

20

In [13]:
# columns
df2.columns

Index(['ProductID', 'ProductName', 'Category', 'QuantityInStock', 'UnitPrice',
       'Supplier', 'DateAdded', 'Warehouse'],
      dtype='object')

In [14]:
# data_types
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ProductID        20 non-null     int64
 1   ProductName      20 non-null     object
 2   Category         20 non-null     object
 3   QuantityInStock  20 non-null     int64
 4   UnitPrice        20 non-null     float64
 5   Supplier         20 non-null     object
 6   DateAdded        20 non-null     object
 7   Warehouse        20 non-null     object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.4+ KB